### PR TITLE
Add "when" arguments to define-obsolete-variable-alias invocations

### PR DESCRIPTION
**Pull request by CyberShadow**
See: https://github.com/emacs-mirror/emacs/commit/32c6732d16385f242b1109517f25e9aefd6caa5c

### CODE REVIEW

**Comment by z3t0** [comment]
Thank you for sharing this update, I've been confused by the error for a while and I didn't know what the issue was! 
Looking forward to it landing in master.

**Comment by daviderestivo** [comment]
@Malabarba may I kindly ask if you got a chance to look into this PR?

**Comment by daviderestivo** [comment]
Up :)

**Comment by hjpotter92** [comment]
Resolved #251

**Comment by Malabarba** [comment]
Merged! Sorry for the radio silence. 

I confess I didn't get this error even though I'm on the latest emacs builds. But I guess it's because SML hasn't had updates and the error is only during byte-compilation?

**Comment by daviderestivo** [comment]
> I confess I didn't get this error even though I'm on the latest emacs builds. But I guess it's because SML hasn't had updates and the error is only during byte-compilation?

Correct ... the error appears on during byte-compilation.

**Pull request merged**
